name: 'Terraform Apply'

on:
  workflow_dispatch:
    inputs:
      AWS_ACCESS_KEY_ID:
        description: 'Your AWS Access Key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'Your AWS Secret Access Key'
        required: true
      AWS_REGION:
        description: 'Your AWS Default Region (e.g., us-west-1)'
        required: true
        default: 'us-west-1'
      VERIFIED_EMAIL:
        description: 'The email address from which emails will be sent'
        required: true

jobs:
  apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ github.event.inputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ github.event.inputs.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.AWS_REGION }}

      # Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # Apply Terraform configuration
      - name: Terraform Apply
        run: >
          terraform apply -auto-approve \
            -var="verified_email=${{ github.event.inputs.verified_email }}" \
            -var="aws_region=${{ github.event.inputs.aws_region }}"
        working-directory: ./terraform

